### ISSUE TITLE
Invalid Hook Call

### ISSUE THREAD

**Issue by Choc13** [formcarry/formcarry-react#2]
I've just installed `@formcarry/react@1.0.2`. When I run my app I see the following error from React.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

I think this is being caused by problem 3 in the list, i.e. two copies of react. Reading the linked documentation it suggests running `npm ls react` to see which versions of react are installed in the deps tree. Running that shows me this.

```
├─┬ @formcarry/react@1.0.2
│ ├─┬ react-dom@16.14.0
│ │ └── react@16.14.0 deduped
│ └── react@16.14.0
├─┬ @netlify/plugin-nextjs@3.4.2
│ └─┬ @sls-next/lambda-at-edge@1.8.0
│   └─┬ @aws-sdk/client-s3@1.0.0-rc.3
│     └─┬ @aws-sdk/middleware-retry@1.0.0-rc.3
│       └─┬ react-native-get-random-values@1.7.0
│         └─┬ react-native@0.64.2
│           └── react@17.0.1
├─┬ next@11.0.1
│ ├─┬ @next/react-dev-overlay@11.0.1
│ │ └── react@17.0.2 deduped
│ ├── react@17.0.2 deduped
│ ├─┬ styled-jsx@3.3.2
│ │ └── react@17.0.2 deduped
│ └─┬ use-subscription@1.5.1
│   └── react@17.0.2 deduped
├─┬ react-dom@17.0.2
│ └── react@17.0.2 deduped
└── react@17.0.2
``` 

Which does show that there are two versions of react installed at different versions.

I think `@formcarry/react` should have a peer dependency on `react` instead of a hard dependency to avoid this duplication issue. This [SO answer](https://stackoverflow.com/questions/30451556/what-is-the-correct-way-of-adding-a-dependency-to-react-in-your-package-json-for) supports this as the correct fix too.

I'll open a PR now to change it over as it should be straight forward.

**Comment by nusu** [comment]
Ohhh totally missed that, thanks for the heads up, I will release the fix ASAP.
