### ISSUE TITLE
Issues with typescript as peer dependency

### ISSUE THREAD

**Issue by heggemsnes** [formcarry/formcarry-react#8]
Hi

We're getting issues with this package due to the outdated typescript dependency. I would think typescript should only be a dev dependency anyways...

![CleanShot 2022-09-06 at 19 48 40](https://user-images.githubusercontent.com/36757859/188704601-060cb08e-469b-45d5-8ecc-2650b1404efe.png)

**Comment by creabik** [comment]
any help guys

**Comment by nusu** [comment]
Fixed in #11, I've also changed the build system so it should work better now with libraries like Next.js

I'm gonna keep this open for 7 days if you like to try and give feedback.
